# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Logeek
email: iman@jsdecorator.com
description: > # Logeek is a javascript log framework for node or browser. It’s a high performance and light weight. Easy to combined with other tools such as Chalk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Iman_Mh
github_username:  ImanMh

# Build settings
markdown: kramdown
